server {
   listen       80;
   server_name  pre-admin.beambox.app;
   charset utf-8;

   client_header_timeout 1m;
   client_body_timeout 1m;
   proxy_connect_timeout 60s;
   proxy_read_timeout 1m;
   proxy_send_timeout 1m;
   client_max_body_size 1024M; #限制文件大小

   location / {
      root   /home/webapp/dist;
      index  index.html index.htm;
      try_files $uri $uri/ /index.html;

      # Enable CORS
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
      if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
      }
   }

   location /dev-api/ {
      proxy_pass https://pre-gateway.beambox.app/;
      # proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect default;
      # 关闭请求体缓冲，让文件上传进度能实时传递给浏览器
      proxy_request_buffering off;
      add_header Access-Control-Allow-Origin *;
      add_header Access-Control-Allow-Headers X-Requested-With;
      add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
   }

   # 避免actuator暴露
   if ($request_uri ~ "/actuator") {
      return 403;
   }

   error_page   500 502 503 504  /50x.html;

   location = /50x.html {
      root   html;
   }
}
